/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.ClienteFisicoData;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteFisicoModel;
import model.TelefoneModel;

/**
 *
 * @author Henrique Borges
 */
public class JIFCadastroClientesFis extends javax.swing.JInternalFrame {

    ClienteFisicoModel obj;
    ArrayList<ClienteFisicoModel> listaCliFisico;
    String acao;
    
    public JIFCadastroClientesFis() {
        initComponents();
        obj = new ClienteFisicoModel();
        listaCliFisico = new ArrayList<>();
        acao = new String();
        inicializarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jspTabelaDados = new javax.swing.JScrollPane();
        jtTabelaDados = new javax.swing.JTable();
        jlPesquisar = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jcbTipoPesquisa = new javax.swing.JComboBox<>();
        jlId = new javax.swing.JLabel();
        jlNumid = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jspTabelaTel = new javax.swing.JScrollPane();
        jtTabelaTel = new javax.swing.JTable();
        jlTelefones = new javax.swing.JLabel();
        jlDdd = new javax.swing.JLabel();
        jtfDdd = new javax.swing.JTextField();
        jlNumeroTel = new javax.swing.JLabel();
        jtfNumeroTel = new javax.swing.JTextField();
        jlTipoTel = new javax.swing.JLabel();
        jcbTipoTel = new javax.swing.JComboBox<>();
        jbAdicionarTel = new javax.swing.JButton();
        jbRemoverTel = new javax.swing.JButton();
        jtfNome = new javax.swing.JTextField();
        jlRua = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jlObservacoes = new javax.swing.JLabel();
        jtfObservacoes = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        jlRg = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlCep = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jlComplemento = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jlData_nasc = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlBairro = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jftfCpf = new javax.swing.JFormattedTextField();
        jftfRg = new javax.swing.JFormattedTextField();
        jftfData_nasc = new javax.swing.JFormattedTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jftfCep = new javax.swing.JFormattedTextField();
        jbVoltar = new javax.swing.JButton();

        jtTabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaDadosMouseClicked(evt);
            }
        });
        jspTabelaDados.setViewportView(jtTabelaDados);

        jlPesquisar.setText("Pesquisar");

        jtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarActionPerformed(evt);
            }
        });
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jcbTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspTabelaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jlPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisar)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTabelaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlId.setText("ID");

        jlNumid.setText("0");

        jlNome.setText("Nome");

        jtTabelaTel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDD", "Número", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabelaTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaTelMouseClicked(evt);
            }
        });
        jspTabelaTel.setViewportView(jtTabelaTel);

        jlTelefones.setText("Telefones");

        jlDdd.setText("DDD");

        jlNumeroTel.setText("Número");

        jlTipoTel.setText("Tipo");

        jcbTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Celular", "Comercial", "Whatsapp", "Outros" }));

        jbAdicionarTel.setText("+");
        jbAdicionarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarTelActionPerformed(evt);
            }
        });

        jbRemoverTel.setText("-");
        jbRemoverTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jlTipoTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAdicionarTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbRemoverTel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jlDdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNumeroTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNumeroTel)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jlTelefones)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jspTabelaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jlTelefones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDdd)
                    .addComponent(jtfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumeroTel)
                    .addComponent(jtfNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoTel)
                    .addComponent(jcbTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarTel)
                    .addComponent(jbRemoverTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTabelaTel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jlRua.setText("Rua");

        jlObservacoes.setText("Observações");

        jlCpf.setText("CPF");

        jlRg.setText("RG");

        jlEmail.setText("Email");

        jlCep.setText("CEP");

        jlCidade.setText("Cidade");

        jlComplemento.setText("Complemento");

        jlNumero.setText("Número");

        jlEstado.setText("Estado");

        jlSexo.setText("Sexo");

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));

        jlData_nasc.setText("Data de nascimento");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlBairro.setText("Bairro");

        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfData_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jlObservacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfBairro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCpf)
                            .addComponent(jlRg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jftfRg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlData_nasc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCidade)
                            .addComponent(jlCep)
                            .addComponent(jlRua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRua)
                            .addComponent(jtfCidade)
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplemento))
                    .addComponent(jtfObservacoes))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jftfData_nasc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNumid)
                        .addGap(265, 265, 265)
                        .addComponent(jbVoltar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addGap(91, 91, 91))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlId)
                            .addComponent(jlNumid)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf)
                            .addComponent(jlSexo)
                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRg)
                            .addComponent(jlData_nasc)
                            .addComponent(jftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfData_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmail)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCep)
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCidade)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRua)
                            .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNumero)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlComplemento)
                            .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstado)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbCancelar))
                .addGap(2, 2, 2)
                .addComponent(jlObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfObservacoes)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos(); //limpa os campos
        tratarCampos(true);//habilitar campos
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jtfNome.requestFocus();
        acao = "incluir";
        jbAdicionarTel.setEnabled(true);
        jtfNumero.setEnabled(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        acao = "editar";
        tratarCampos(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbAdicionarTel.setEnabled(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparCampos();
        tratarCampos(false);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbAdicionarTel.setEnabled(false);
        jtTabelaTel.removeAll();
        limparTabDadosFunc();
        limparTabelaTel();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    //if(incluir(obj)){
                    ClienteFisicoData DAO = new ClienteFisicoData();
                    if(acao.equals("incluir")){
                        if(DAO.incluir(obj)){
                            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                            jbCancelarActionPerformed(evt);
                        }   
                        else{
                        JOptionPane.showMessageDialog(null, "Erro ao salvar!");
                        }
                    }else{
                        if(acao.equals("editar")){
                            if(DAO.alterar(obj)){
                                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                                jbCancelarActionPerformed(evt);
                            }else
                                JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                        }
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage() + "Salvar" + JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarTelActionPerformed
        try{
            if(jtfDdd.getText().trim().length() != 2 || 
                    jtfNumeroTel.getText().trim().length() < 8 || jtfNumeroTel.getText().trim().length() > 9){
                JOptionPane.showMessageDialog(this, "Verifique os campos");
            }else{
                DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
                if(verificaTelRep(mp, jtfDdd.getText(), jtfNumeroTel.getText())){
                    JOptionPane.showMessageDialog(this, "Telefone repetido! Verifique o número");
                }else{
                    mp.addRow(new String[]{jtfDdd.getText(), jtfNumeroTel.getText(), jcbTipoTel.getSelectedItem().toString()});
                jtfDdd.setText("");
                jtfNumeroTel.setText("");
                jcbTipoTel.setSelectedIndex(0);
                }
            }
        
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                    
        }
    }//GEN-LAST:event_jbAdicionarTelActionPerformed

    private void jbRemoverTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverTelActionPerformed
        try{
            int linha = jtTabelaTel.getSelectedRow();
            DefaultTableModel mp = (DefaultTableModel)jtTabelaTel.getModel();
            mp.removeRow(linha);
            jtTabelaTel.clearSelection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jbRemoverTelActionPerformed

    private void jtTabelaTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaTelMouseClicked
        
    }//GEN-LAST:event_jtTabelaTelMouseClicked

    private void jtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarActionPerformed
        
    }//GEN-LAST:event_jtfPesquisarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try{
            String pesq = jtfPesquisar.getText();
            if(pesq.length() > 2){
                ClienteFisicoData DAO = new ClienteFisicoData();
                listaCliFisico = DAO.pesquisar(pesq);
                DefaultTableModel mp = (DefaultTableModel) jtTabelaDados.getModel();
                mp.setNumRows(0);
                for(ClienteFisicoModel u: listaCliFisico){
                    mp.addRow(new String[]{"" + u.getId(), u.getNome(), u.getCpf(), u.getEmail()});
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro: "+erro.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtTabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaDadosMouseClicked
        try{
            int linha = jtTabelaDados.getSelectedRow();
            if(linha>-1){
                jlNumid.setText("" + listaCliFisico.get(linha).getId());
                jtfNome.setText(listaCliFisico.get(linha).getNome());
                jtfCidade.setText(listaCliFisico.get(linha).getCidade());
                jtfRua.setText(listaCliFisico.get(linha).getRua());
                jtfBairro.setText(listaCliFisico.get(linha).getBairro());
                jtfEmail.setText(listaCliFisico.get(linha).getEmail());
                jftfCpf.setText(listaCliFisico.get(linha).getCpf());
                jftfData_nasc.setText(listaCliFisico.get(linha).getData_nasc());
                jftfCep.setText(listaCliFisico.get(linha).getCep());
                jtfNumero.setText(listaCliFisico.get(linha).getNumero());
                jcbEstado.setSelectedItem(listaCliFisico.get(linha).getEstado());
                jtfEmail.setText(listaCliFisico.get(linha).getEmail());
                jtfComplemento.setText(listaCliFisico.get(linha).getComplemento());
                jcbSexo.setSelectedItem(listaCliFisico.get(linha).getSexo());
                jftfRg.setText(listaCliFisico.get(linha).getRg());
                jtfObservacoes.setText(listaCliFisico.get(linha).getObservacoes());
                DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
                mp.setNumRows(0);
                for(TelefoneModel tel: listaCliFisico.get(linha).getTelefones()){
                    mp.addRow(new String[]{"" + tel.getDdd(), "" + tel.getNumero(), tel.getTipo_tel()});
                }
                jbEditar.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jtTabelaDadosMouseClicked

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbAdicionarTel;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRemoverTel;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbTipoPesquisa;
    private javax.swing.JComboBox<String> jcbTipoTel;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfData_nasc;
    private javax.swing.JFormattedTextField jftfRg;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlData_nasc;
    private javax.swing.JLabel jlDdd;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlNumeroTel;
    private javax.swing.JLabel jlNumid;
    private javax.swing.JLabel jlObservacoes;
    private javax.swing.JLabel jlPesquisar;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTelefones;
    private javax.swing.JLabel jlTipoTel;
    private javax.swing.JScrollPane jspTabelaDados;
    private javax.swing.JScrollPane jspTabelaTel;
    private javax.swing.JTable jtTabelaDados;
    private javax.swing.JTable jtTabelaTel;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfDdd;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfNumeroTel;
    private javax.swing.JTextField jtfObservacoes;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfRua;
    // End of variables declaration//GEN-END:variables
    public void tratarCampos(boolean t){
        jtfNome.setEnabled(t);
        jtfCidade.setEnabled(t);
        jtfRua.setEnabled(t);
        jtfBairro.setEnabled(t);
        jtfEmail.setEnabled(t);
        jftfCpf.setEnabled(t);
        jftfCep.setEnabled(t);
        jtfNumero.setEnabled(t);
        jcbEstado.setEnabled(t);
        jtfComplemento.setEnabled(t);
        jcbSexo.setEnabled(t);
        jftfRg.setEnabled(t);
        jcbTipoTel.setEnabled(t);
        jtfDdd.setEnabled(t);
        jtfNumeroTel.setEnabled(t);
        jtfObservacoes.setEnabled(t);
        jftfData_nasc.setEnabled(t);
        jbAdicionarTel.setEnabled(t);
        jbRemoverTel.setEnabled(t);
    }
    
    public void limparCampos(){
        jlNumid.setText("0");
        jtfNome.setText(null);
        jtfCidade.setText(null);
        jtfRua.setText(null);
        jtfBairro.setText(null);
        jtfEmail.setText(null);
        jftfCpf.setText(null);
        jftfData_nasc.setText(null);
        jftfCep.setText(null);
        jtfNumero.setText(null);
        jcbEstado.setSelectedIndex(0);
        jtfComplemento.setText(null);
        jcbSexo.setSelectedIndex(0);
        jftfRg.setText(null);
        jcbTipoTel.setSelectedIndex(0);
        jtfDdd.setText(null);
        jtfNumeroTel.setText(null);
        jtfObservacoes.setText(null);
    }
    
    public boolean validarCampos(){
        try{
            String msg = new String();
            ClienteFisicoData fis = new ClienteFisicoData();
            if(jtfNome.getText().trim().length()<3)
            msg = "Verifique o nome";
            if(jtfEmail.getText().trim().length()<10 || !jtfEmail.getText().trim().contains("@"))
                msg += "\nVerifique o e-mail";
            if(jftfCpf.getText().trim().length() != 14)
                msg += "\nVerifique o CPF";
            if(jftfRg.getText().trim().length() != 12)
                msg+= "\nVerifique o RG";
            if(jftfCep.getText().trim().length() != 10)
                msg += "\nVerifique o Cep";
            if(jtfRua.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da rua";
            if(jtfBairro.getText().trim().length() < 3)
                msg+= "\nVerifique o nome o bairro";
            if(jtfCidade.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da cidade";
            if(jtfRua.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da rua";
            if(jtfNumero.getText().trim().length() > 5)
                msg+= "\nVerifique o numero do endereço";
            if(jcbEstado.getSelectedIndex() == 0)
                msg+= "\nVerifique o estado";
            if(jftfData_nasc.getText().trim().length() != 10)
                msg+= "\nVerifique a data de nascimento";
            if(jcbSexo.getSelectedIndex() == 0)
                msg+= "\nVerifique o sexo";
            if(fis.verificaCpf(jftfCpf.getText()))
                msg += "\nCPF já em uso!";
            if(fis.verificaRg(jftfRg.getText()))
                    msg += "\nRg já em uso!";
            if(msg.isEmpty()) return true;
            else{
                JOptionPane.showMessageDialog(this, "Erros: " + msg, "Validação", JOptionPane.ERROR_MESSAGE);
                return false;        
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        return false;
    }
    
    public boolean preencherObjeto() throws Exception{
        obj.setId(Integer.parseInt(jlNumid.getText()));
        obj.setNome(jtfNome.getText());
        obj.setCidade(jtfCidade.getText());
        obj.setRua(jtfRua.getText());
        obj.setBairro(jtfBairro.getText());
        obj.setEmail(jtfEmail.getText());
        obj.setCpf(jftfCpf.getText());
        obj.setData_nasc(jftfData_nasc.getText());
        obj.setCep(jftfCep.getText());
        obj.setNumero(jtfNumero.getText());
        obj.setEstado(jcbEstado.getSelectedItem().toString());
        obj.setComplemento(jtfComplemento.getText());
        obj.setSexo(jcbSexo.getSelectedItem().toString());
        obj.setRg(jftfRg.getText());
        obj.setObservacoes(jtfObservacoes.getText());
        DefaultTableModel mp = (DefaultTableModel)jtTabelaTel.getModel();
            for(int i=0; i<mp.getRowCount(); i++){
                TelefoneModel telefone = new TelefoneModel();
                telefone.setDdd(Integer.parseInt(mp.getValueAt(i, 0).toString()));
                telefone.setNumero(Integer.parseInt(mp.getValueAt(i, 1).toString()));
                telefone.setTipo_tel(mp.getValueAt(i, 2).toString());
                obj.adicionarTelefone(telefone);
            }
            return true;
    }

    public void inicializarTela(){
        limparCampos();
        tratarCampos(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }
    
    public void limparTabelaTel(){
        DefaultTableModel tabela = (DefaultTableModel) jtTabelaTel.getModel();
        for(int i = tabela.getRowCount() - 1; i>=0; i--)
            tabela.removeRow(i);
    }
    public void limparTabDadosFunc(){
        DefaultTableModel tabela = (DefaultTableModel) jtTabelaDados.getModel();
        for(int i = tabela.getRowCount() - 1; i>=0; i--)
            tabela.removeRow(i);
        jtfPesquisar.setText("");
    }
    
    public boolean verificaTelRep(DefaultTableModel mp, String ddd, String numero){
        int quant = mp.getRowCount();
        while(quant != 0){
            if(mp.getValueAt(mp.getRowCount() - 1, 0).equals(ddd) && mp.getValueAt(mp.getRowCount() - 1, 1).equals(numero))
                return true;
            quant--;
        }
        return false;
    }
            
}
