/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
//PROBLEMA COM A DATA DE NASCIMENTO, ADICIONA O TELEFONE E APENAS O DDD LIMPA, O NUMERO CONTINUA
//SO PERMITE INCLUIR O TELEFONE SE O NUMERO DA CASA ESTIVER PREENCHIDO
//DEPOIS DE REMOVER UM TELEFONE O - DESABILITA

import data.ClienteJuriData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteJuridicoModel;
import model.TelefoneModel;

/**
 *
 * @author Henrique Borges
 */
public class jifCadastroClientesJuri extends javax.swing.JInternalFrame {

    ClienteJuridicoModel obj;
    ArrayList<ClienteJuridicoModel> listaCliJuri;
    String acao;

    public jifCadastroClientesJuri() {
        initComponents();
        obj = new ClienteJuridicoModel();
        listaCliJuri = new ArrayList<>();
        acao = new String();
        inicializarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jspTabelaTel = new javax.swing.JScrollPane();
        jtTabelaTel = new javax.swing.JTable();
        jlTelefones = new javax.swing.JLabel();
        jlDdd = new javax.swing.JLabel();
        jtfDdd = new javax.swing.JTextField();
        jlNumeroTel = new javax.swing.JLabel();
        jtfNumeroTel = new javax.swing.JTextField();
        jlTipo = new javax.swing.JLabel();
        jcbTipoTel = new javax.swing.JComboBox<>();
        jbAdicionarTel = new javax.swing.JButton();
        jbRemoverTel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jspTabelaDados = new javax.swing.JScrollPane();
        jtTabelaDados = new javax.swing.JTable();
        jlPesquisar = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jcbPesquisar = new javax.swing.JComboBox<>();
        jlId = new javax.swing.JLabel();
        jlNumid = new javax.swing.JLabel();
        jlNomeFant = new javax.swing.JLabel();
        jtfNomeFant = new javax.swing.JTextField();
        jlRazaoSocial = new javax.swing.JLabel();
        jtfRazaoSocial = new javax.swing.JTextField();
        jlCnpj = new javax.swing.JLabel();
        jlCep = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jlBairro = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jlRua = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlObservacoes = new javax.swing.JLabel();
        jtfObservacoes = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jlComplemento = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jftfCep = new javax.swing.JFormattedTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jftfCnpj = new javax.swing.JFormattedTextField();

        jtTabelaTel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDD", "Número", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabelaTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaTelMouseClicked(evt);
            }
        });
        jspTabelaTel.setViewportView(jtTabelaTel);

        jlTelefones.setText("Telefones");

        jlDdd.setText("DDD");

        jlNumeroTel.setText("Número");

        jlTipo.setText("Tipo");

        jcbTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Celular", "Comercial", "Whatsapp", "Outros" }));

        jbAdicionarTel.setText("+");
        jbAdicionarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarTelActionPerformed(evt);
            }
        });

        jbRemoverTel.setText("-");
        jbRemoverTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jspTabelaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jlTelefones))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jlTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTipoTel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jlDdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jlNumeroTel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbAdicionarTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbRemoverTel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTelefones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDdd)
                    .addComponent(jtfDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumeroTel)
                    .addComponent(jtfNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(jcbTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarTel)
                    .addComponent(jbRemoverTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTabelaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtTabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Fantasia", "Razão Social", "CNPJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaDadosMouseClicked(evt);
            }
        });
        jspTabelaDados.setViewportView(jtTabelaDados);

        jlPesquisar.setText("Pesquisar");

        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jcbPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspTabelaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisar)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTabelaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlId.setText("ID");

        jlNumid.setText("0");

        jlNomeFant.setText("Nome Fantasia");

        jlRazaoSocial.setText("Razão Social");

        jlCnpj.setText("CNPJ");

        jlCep.setText("Cep");

        jlCidade.setText("Cidade");

        jlBairro.setText("Bairro");

        jlRua.setText("Rua");

        jlEstado.setText("Estado");

        jlNumero.setText("Número");

        jlEmail.setText("Email");

        jlObservacoes.setText("Observações");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlComplemento.setText("Complemento");

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            jftfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlNomeFant)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlRazaoSocial)
                                    .addGap(15, 15, 15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCnpj)
                                    .addComponent(jlEmail)
                                    .addComponent(jlCep)
                                    .addComponent(jlCidade)
                                    .addComponent(jlBairro))
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(jtfBairro, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfRazaoSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfNomeFant, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlRua)
                                    .addComponent(jlNumero)
                                    .addComponent(jlEstado))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jbNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNumid)
                        .addGap(349, 349, 349)
                        .addComponent(jbVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jtfObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jlObservacoes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId)
                    .addComponent(jlNumid)
                    .addComponent(jbVoltar))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNomeFant)
                            .addComponent(jtfNomeFant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRazaoSocial)
                            .addComponent(jtfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCnpj)
                            .addComponent(jftfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmail)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCep)
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCidade)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBairro)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRua))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumero)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstado)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNovo)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar)
                            .addComponent(jbCancelar)
                            .addComponent(jbExcluir))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlComplemento)
                            .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlObservacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfObservacoes)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCampos(); //limpa os campos
        tratarCampos(true);//habilitar campos
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jtfNomeFant.requestFocus();
        acao = "incluir";
        jbAdicionarTel.setEnabled(true);
        jtfNumero.setEnabled(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    //if(incluir(obj)){
                    ClienteJuriData DAO = new ClienteJuriData();
                    if (acao.equals("incluir")) {
                        if (DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                            jbCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Erro ao salvar!");
                        }
                    } else {
                        if (acao.equals("editar")) {
                            if (DAO.alterar(obj)) {
                                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                                jbCancelarActionPerformed(evt);
                            } else {
                                JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                            }
                        }
                    }
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage() + "Salvar" + JOptionPane.INFORMATION_MESSAGE);
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        acao = "editar";
        tratarCampos(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbAdicionarTel.setEnabled(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparCampos();
        tratarCampos(false);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbAdicionarTel.setEnabled(false);
        limparTabDadosCli();
        limparTabelaTel();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?",
                    "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                ClienteJuriData DAO = new ClienteJuriData();
                if (DAO.excluir(Integer.parseInt(jlNumid.getText()))) {
                    JOptionPane.showMessageDialog(this, "Excluido");
                    jbCancelarActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarTelActionPerformed
        try {
            if (jtfDdd.getText().trim().length() != 2
                    || jtfNumeroTel.getText().trim().length() < 8 || jtfNumeroTel.getText().trim().length() > 9) {
                JOptionPane.showMessageDialog(this, "Verifique os campos");
            } else {
                DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
                if (verificaTelRep(mp, jtfDdd.getText(), jtfNumeroTel.getText())) {
                    JOptionPane.showMessageDialog(this, "Telefone repetido! Verifique o número");
                } else {
                    mp.addRow(new String[]{jtfDdd.getText(), jtfNumeroTel.getText(), jcbTipoTel.getSelectedItem().toString()});
                    jtfDdd.setText("");
                    jtfNumeroTel.setText("");
                    jcbTipoTel.setSelectedIndex(0);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());

        }
    }//GEN-LAST:event_jbAdicionarTelActionPerformed

    private void jbRemoverTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverTelActionPerformed
        try {
            int linha = jtTabelaTel.getSelectedRow();
            DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
            mp.removeRow(linha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jbRemoverTelActionPerformed

    private void jtTabelaTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaTelMouseClicked
        try {
            int linha = jtTabelaTel.getSelectedRow();
            if (linha > -1) {
                jbExcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jtTabelaTelMouseClicked

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try {
            String pesq = jtfPesquisar.getText();
            if (pesq.length() > 2) {
                ClienteJuriData DAO = new ClienteJuriData();
                listaCliJuri = DAO.pesquisar(pesq);
                DefaultTableModel mp = (DefaultTableModel) jtTabelaDados.getModel();
                mp.setNumRows(0);
                for (ClienteJuridicoModel u : listaCliJuri) {
                    mp.addRow(new String[]{"" + u.getId(), u.getNome_fant(), u.getRazao_social(), u.getCnpj()});
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtTabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaDadosMouseClicked
        try {
            int linha = jtTabelaDados.getSelectedRow();
            if (linha > -1) {
                jlNumid.setText("" + listaCliJuri.get(linha).getId());
                jtfNomeFant.setText(listaCliJuri.get(linha).getNome_fant());
                jftfCnpj.setText(listaCliJuri.get(linha).getCnpj());
                jtfRazaoSocial.setText(listaCliJuri.get(linha).getRazao_social());
                jtfCidade.setText(listaCliJuri.get(linha).getCidade());
                jtfRua.setText(listaCliJuri.get(linha).getRua());
                jtfBairro.setText(listaCliJuri.get(linha).getBairro());
                jtfEmail.setText(listaCliJuri.get(linha).getEmail());
                jftfCep.setText(listaCliJuri.get(linha).getCep());
                jtfNumero.setText(listaCliJuri.get(linha).getNumero());
                jcbEstado.setSelectedItem(listaCliJuri.get(linha).getEstado());
                jtfComplemento.setText(listaCliJuri.get(linha).getComplemento());
                jtfObservacoes.setText(listaCliJuri.get(linha).getObservacoes());
                DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
                mp.setNumRows(0);
                for (TelefoneModel tel : listaCliJuri.get(linha).getTelefones()) {
                    mp.addRow(new String[]{"" + tel.getDdd(), "" + tel.getNumero(), tel.getTipo_tel()});
                }
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    /*
    private void jtTabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {                                           
        
    }//GEN-LAST:event_jtTabelaDadosMouseClicked
*/
    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbAdicionarTel;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRemoverTel;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbPesquisar;
    private javax.swing.JComboBox<String> jcbTipoTel;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfCnpj;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCnpj;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlDdd;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNomeFant;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlNumeroTel;
    private javax.swing.JLabel jlNumid;
    private javax.swing.JLabel jlObservacoes;
    private javax.swing.JLabel jlPesquisar;
    private javax.swing.JLabel jlRazaoSocial;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlTelefones;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JScrollPane jspTabelaDados;
    private javax.swing.JScrollPane jspTabelaTel;
    private javax.swing.JTable jtTabelaDados;
    private javax.swing.JTable jtTabelaTel;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfDdd;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNomeFant;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfNumeroTel;
    private javax.swing.JTextField jtfObservacoes;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfRazaoSocial;
    private javax.swing.JTextField jtfRua;
    // End of variables declaration//GEN-END:variables

    public void tratarCampos(boolean t) {
        jtfNomeFant.setEnabled(t);
        jtfRazaoSocial.setEnabled(t);
        jtfCidade.setEnabled(t);
        jtfRua.setEnabled(t);
        jtfBairro.setEnabled(t);
        jtfEmail.setEnabled(t);
        jftfCnpj.setEnabled(t);
        jftfCep.setEnabled(t);
        jtfNumero.setEnabled(t);
        jcbEstado.setEnabled(t);
        jtfComplemento.setEnabled(t);
        jcbTipoTel.setEnabled(t);
        jtfDdd.setEnabled(t);
        jtfNumeroTel.setEnabled(t);
        jtfObservacoes.setEnabled(t);
        jbAdicionarTel.setEnabled(t);
        jbRemoverTel.setEnabled(t);
    }

    public void limparCampos() {
        jlNumid.setText("0");
        jtfNomeFant.setText(null);
        jtfRazaoSocial.setText(null);
        jtfCidade.setText(null);
        jtfRua.setText(null);
        jtfBairro.setText(null);
        jtfEmail.setText(null);
        jftfCnpj.setText(null);
        jftfCep.setText(null);
        jtfNumero.setText(null);
        jcbEstado.setSelectedIndex(0);
        jtfComplemento.setText(null);
        jcbTipoTel.setSelectedIndex(0);
        jtfDdd.setText(null);
        jtfNumeroTel.setText(null);
        jtfObservacoes.setText(null);
    }

    public boolean validarCampos() {
        String msg = new String();
        if (jtfNomeFant.getText().trim().length() < 3) {
            msg = "Verifique o nome";
        }
        if (jtfRazaoSocial.getText().trim().length() < 3) {
            msg = "Verifique a razão social";
        }
        if (jtfEmail.getText().trim().length() < 10 || !jtfEmail.getText().trim().contains("@")) {
            msg += "\nVerifique o e-mail";
        }
        if (jftfCnpj.getText().trim().length() != 18) {
            msg += "\nVerifique o CPF";
        }
        if (jftfCep.getText().trim().length() != 10) {
            msg += "\nVerifique o Cep";
        }
        if (jtfRua.getText().trim().length() < 3) {
            msg += "\nVerifique o nome da rua";
        }
        if (jtfBairro.getText().trim().length() < 3) {
            msg += "\nVerifique o nome o bairro";
        }
        if (jtfCidade.getText().trim().length() < 3) {
            msg += "\nVerifique o nome da cidade";
        }
        if (jtfRua.getText().trim().length() < 3) {
            msg += "\nVerifique o nome da rua";
        }
        if (jtfNumero.getText().trim().length() > 5) {
            msg += "\nVerifique o numero do endereço";
        }
        if (jcbEstado.getSelectedIndex() == 0) {
            msg += "\nVerifique o nome da rua";
        }
        if (msg.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erros: " + msg, "Validação", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public boolean preencherObjeto() throws Exception {
        obj.setId(Integer.parseInt(jlNumid.getText()));
        obj.setNome_fant(jtfNomeFant.getText());
        obj.setRazao_social(jtfRazaoSocial.getText());
        obj.setCidade(jtfCidade.getText());
        obj.setRua(jtfRua.getText());
        obj.setBairro(jtfBairro.getText());
        obj.setEmail(jtfEmail.getText());
        obj.setCnpj(jftfCnpj.getText());
        obj.setCep(jftfCep.getText());
        obj.setNumero(jtfNumero.getText());
        obj.setEstado(jcbEstado.getSelectedItem().toString());
        obj.setComplemento(jtfComplemento.getText());
        obj.setObservacoes(jtfObservacoes.getText());
        DefaultTableModel mp = (DefaultTableModel) jtTabelaTel.getModel();
        for (int i = 0; i < mp.getRowCount(); i++) {
            TelefoneModel telefone = new TelefoneModel();
            telefone.setDdd(Integer.parseInt(mp.getValueAt(i, 0).toString()));
            telefone.setNumero(Integer.parseInt(mp.getValueAt(i, 1).toString()));
            telefone.setTipo_tel(mp.getValueAt(i, 2).toString());
            obj.adicionarTelefone(telefone);
        }
        return true;
    }

    public void inicializarTela() {
        limparCampos();
        tratarCampos(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbExcluir.setEnabled(false);
    }

    public void limparTabelaTel() {
        DefaultTableModel tabela = (DefaultTableModel) jtTabelaTel.getModel();
        for (int i = tabela.getRowCount() - 1; i >= 0; i--) {
            tabela.removeRow(i);
        }
    }

    public void limparTabDadosCli() {
        DefaultTableModel tabela = (DefaultTableModel) jtTabelaDados.getModel();
        for (int i = tabela.getRowCount() - 1; i >= 0; i--) {
            tabela.removeRow(i);
        }
        jtfPesquisar.setText("");
    }

    public boolean verificaTelRep(DefaultTableModel mp, String ddd, String numero) {
        int quant = mp.getRowCount();
        while (quant != 0) {
            if (mp.getValueAt(mp.getRowCount() - 1, 0).equals(ddd) && mp.getValueAt(mp.getRowCount() - 1, 1).equals(numero)) {
                return true;
            }
            quant--;
        }
        return false;
    }
}
