/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.FuncionarioData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;
import model.TelefoneModel;

/**
 *
 * @author Henrique Borges
 */
public class JIFCadastroFuncionarios extends javax.swing.JInternalFrame {
    FuncionarioModel obj;
    ArrayList<FuncionarioModel> listaFuncionarios;
    String acao;
    
    public JIFCadastroFuncionarios() {
        initComponents();
        obj = new FuncionarioModel();
        listaFuncionarios = new ArrayList<>();
        acao = new String();
        inicializarTela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPTabela = new javax.swing.JPanel();
        JSPTabela = new javax.swing.JScrollPane();
        JTTabelaDados = new javax.swing.JTable();
        JLPesquisar = new javax.swing.JLabel();
        JTFPesquisar = new javax.swing.JTextField();
        JBNovo = new javax.swing.JButton();
        JBSalvar = new javax.swing.JButton();
        JBEditar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JLId = new javax.swing.JLabel();
        JLNumid = new javax.swing.JLabel();
        JLNome = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JLCidade = new javax.swing.JLabel();
        JTFCidade = new javax.swing.JTextField();
        JLRua = new javax.swing.JLabel();
        JTFRua = new javax.swing.JTextField();
        JLBairro = new javax.swing.JLabel();
        JTFBairro = new javax.swing.JTextField();
        JLCep = new javax.swing.JLabel();
        JLNumero = new javax.swing.JLabel();
        JTFNumero = new javax.swing.JTextField();
        JLEstado = new javax.swing.JLabel();
        JLTelefone = new javax.swing.JLabel();
        JLDdd = new javax.swing.JLabel();
        JTFDdd = new javax.swing.JTextField();
        JLNumTel = new javax.swing.JLabel();
        JTFNumTel = new javax.swing.JTextField();
        JSPTabelaTel = new javax.swing.JScrollPane();
        JTTabelaTel = new javax.swing.JTable();
        JBAdicionarTel = new javax.swing.JButton();
        JBExcluirTel = new javax.swing.JButton();
        JLCompl = new javax.swing.JLabel();
        JTFCompl = new javax.swing.JTextField();
        JLEmail = new javax.swing.JLabel();
        JTFEmail = new javax.swing.JTextField();
        JLLogin = new javax.swing.JLabel();
        JTFLogin = new javax.swing.JTextField();
        JLSenha = new javax.swing.JLabel();
        JLCpf = new javax.swing.JLabel();
        JLRg = new javax.swing.JLabel();
        JLData_nasc = new javax.swing.JLabel();
        JLSexo = new javax.swing.JLabel();
        JCBCargo = new javax.swing.JComboBox<>();
        JLCargo = new javax.swing.JLabel();
        JCBTipoTel = new javax.swing.JComboBox<>();
        JLObservacoes = new javax.swing.JLabel();
        JTFObservacoes = new javax.swing.JTextField();
        jcbSexo = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JComboBox<>();
        jftfDataNasc = new javax.swing.JFormattedTextField();
        jftfRg = new javax.swing.JFormattedTextField();
        jftfCpf = new javax.swing.JFormattedTextField();
        jtfSenha = new javax.swing.JTextField();
        jftfCep = new javax.swing.JFormattedTextField();
        jbVoltar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));

        JTTabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTTabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTTabelaDadosMouseClicked(evt);
            }
        });
        JSPTabela.setViewportView(JTTabelaDados);

        JLPesquisar.setText("Pesquisar");

        JTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPesquisarActionPerformed(evt);
            }
        });
        JTFPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPTabelaLayout = new javax.swing.GroupLayout(JPTabela);
        JPTabela.setLayout(JPTabelaLayout);
        JPTabelaLayout.setHorizontalGroup(
            JPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTabelaLayout.createSequentialGroup()
                .addGroup(JPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPTabelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JSPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPTabelaLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(JLPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(JTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPTabelaLayout.setVerticalGroup(
            JPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLPesquisar)
                    .addComponent(JTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(JSPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBEditar.setText("Editar");
        JBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBExcluir.setText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JLId.setText("ID");

        JLNumid.setText("0");

        JLNome.setText("Nome");

        JLCidade.setText("Cidade");

        JLRua.setText("Rua");

        JTFRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFRuaActionPerformed(evt);
            }
        });

        JLBairro.setText("Bairro");

        JLCep.setText("CEP");

        JLNumero.setText("Número");

        JLEstado.setText("Estado");

        JLTelefone.setText("Telefones");

        JLDdd.setText("DDD");

        JLNumTel.setText("Número");

        JTTabelaTel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DDD", "Número", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTTabelaTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTTabelaTelMouseClicked(evt);
            }
        });
        JSPTabelaTel.setViewportView(JTTabelaTel);

        JBAdicionarTel.setText("+");
        JBAdicionarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarTelActionPerformed(evt);
            }
        });

        JBExcluirTel.setText("-");
        JBExcluirTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirTelActionPerformed(evt);
            }
        });

        JLCompl.setText("Complemento");

        JLEmail.setText("E-mail");

        JLLogin.setText("Login");

        JLSenha.setText("Senha");

        JLCpf.setText("CPF");

        JLRg.setText("RG");

        JLData_nasc.setText("Data de Nascimento");

        JLSexo.setText("Sexo");

        JCBCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Lojista", "Gerente", " " }));
        JCBCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBCargoActionPerformed(evt);
            }
        });

        JLCargo.setText("Cargo");

        JCBTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Celular", "Comercial", "Whatsapp", "Outros", " " }));

        JLObservacoes.setText("Observações:");

        JTFObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFObservacoesActionPerformed(evt);
            }
        });

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            jftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfDataNascActionPerformed(evt);
            }
        });

        try {
            jftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(JPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVoltar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(JBNovo)
                        .addGap(59, 59, 59)
                        .addComponent(JBSalvar)
                        .addGap(60, 60, 60)
                        .addComponent(JBEditar)
                        .addGap(45, 45, 45)
                        .addComponent(JBCancelar)
                        .addGap(56, 56, 56)
                        .addComponent(JBExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(JLNome)
                        .addGap(10, 10, 10)
                        .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JLSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(JLId)
                        .addGap(10, 10, 10)
                        .addComponent(JLNumid)
                        .addGap(319, 319, 319)
                        .addComponent(JLTelefone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(JLCpf)
                        .addGap(18, 18, 18)
                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(JLData_nasc)
                        .addGap(4, 4, 4)
                        .addComponent(jftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316)
                        .addComponent(JCBTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(JBAdicionarTel)
                        .addGap(18, 18, 18)
                        .addComponent(JBExcluirTel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(JLRg))
                            .addComponent(JLCidade)
                            .addComponent(JLBairro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(JLRua)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(JTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(JTFRua, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLEmail)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLEstado)
                                    .addComponent(JLCep)
                                    .addComponent(JLNumero))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(JTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(JLDdd)
                                .addGap(10, 10, 10)
                                .addComponent(JTFDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(JLNumTel)
                                .addGap(10, 10, 10)
                                .addComponent(JTFNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSPTabelaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(JLCompl)
                        .addGap(10, 10, 10)
                        .addComponent(JTFCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(675, 675, 675)
                        .addComponent(JLObservacoes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLLogin)
                            .addComponent(JLSenha))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151)
                        .addComponent(JLCargo)
                        .addGap(30, 30, 30)
                        .addComponent(JCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331)
                        .addComponent(JTFObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVoltar))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBNovo)
                    .addComponent(JBSalvar)
                    .addComponent(JBEditar)
                    .addComponent(JBCancelar)
                    .addComponent(JBExcluir))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLNome))
                    .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLSexo))
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(JLId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(JLNumid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLTelefone)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JLCpf))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JLData_nasc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JCBTipoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBAdicionarTel)
                    .addComponent(JBExcluirTel))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLRg)
                        .addGap(24, 24, 24)
                        .addComponent(JLCidade)
                        .addGap(24, 24, 24)
                        .addComponent(JLBairro)
                        .addGap(24, 24, 24)
                        .addComponent(JLRua))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLEmail)
                        .addGap(24, 24, 24)
                        .addComponent(JLEstado)
                        .addGap(24, 24, 24)
                        .addComponent(JLCep)
                        .addGap(24, 24, 24)
                        .addComponent(JLNumero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLDdd)
                                    .addComponent(JLNumTel))))
                        .addGap(6, 6, 6)
                        .addComponent(JSPTabelaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLCompl))
                    .addComponent(JTFCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JLObservacoes)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JLLogin)
                        .addGap(24, 24, 24)
                        .addComponent(JLSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(JLCargo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(JCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTFObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPesquisarActionPerformed

    private void JTFRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFRuaActionPerformed

    private void JCBCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBCargoActionPerformed

    private void JTFObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFObservacoesActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        limparCampos(); //limpa os campos
        tratarCampos(true);//habilitar campos
        JBNovo.setEnabled(false);
        JBSalvar.setEnabled(true);
        JBCancelar.setEnabled(true);
        JTFNome.requestFocus();
        acao = "incluir";
        JBAdicionarTel.setEnabled(true);
        JTFNumero.setEnabled(true);
    }//GEN-LAST:event_JBNovoActionPerformed

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    //if(incluir(obj)){
                    FuncionarioData DAO = new FuncionarioData();
                    if(acao.equals("incluir")){
                        if(DAO.incluir(obj)){
                            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                            JBCancelarActionPerformed(evt);
                        }   
                        else{
                        JOptionPane.showMessageDialog(null, "Erro ao salvar!");
                        }
                    }else{
                        if(acao.equals("editar")){
                            if(DAO.alterar(obj)){
                            JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                            JBCancelarActionPerformed(evt);
                        }else{
                            JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                        }
                        }
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage() + "Salvar" + JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        limparCampos();
        tratarCampos(false);
        JBNovo.setEnabled(true);
        JBSalvar.setEnabled(false);
        JBCancelar.setEnabled(false);
        JBAdicionarTel.setEnabled(false);
        limparTabelaTel();
        limparTabDadosFunc();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTFPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFPesquisarKeyReleased
        try{
            String pesq = JTFPesquisar.getText();
            if(pesq.length() > 2){
                FuncionarioData DAO = new FuncionarioData();
                listaFuncionarios = DAO.pesquisar(pesq);
                DefaultTableModel mp = (DefaultTableModel) JTTabelaDados.getModel();
                mp.setNumRows(0);
                for(FuncionarioModel u: listaFuncionarios){
                    mp.addRow(new String[]{"" + u.getId(), u.getNome(), u.getCpf(), u.getCargo()});
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro: "+erro.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JTFPesquisarKeyReleased

    private void JBAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarTelActionPerformed
        try{
            if(JTFDdd.getText().trim().length() != 2 || 
                    JTFNumTel.getText().trim().length() < 8 || JTFNumTel.getText().trim().length() > 9){
                JOptionPane.showMessageDialog(this, "Verifique os campos");
            }else{
                DefaultTableModel mp = (DefaultTableModel) JTTabelaTel.getModel();
                if(verificaTelRep(mp, JTFDdd.getText(), JTFNumTel.getText())){
                    JOptionPane.showMessageDialog(this, "Telefone repetido! Verifique o número");
                }else{
                    mp.addRow(new String[]{JTFDdd.getText(), JTFNumTel.getText(), JCBTipoTel.getSelectedItem().toString()});
                JTFDdd.setText("");
                JTFNumTel.setText("");
                JCBTipoTel.setSelectedIndex(0);
                }
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                    
        }
    }//GEN-LAST:event_JBAdicionarTelActionPerformed

    private void JBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarActionPerformed
        acao = "editar";
        tratarCampos(true);
        JBNovo.setEnabled(false);
        JBSalvar.setEnabled(true);
        JBCancelar.setEnabled(true);
        JBEditar.setEnabled(false);
        JBExcluir.setEnabled(false);
        JBAdicionarTel.setEnabled(true);
    }//GEN-LAST:event_JBEditarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        try{
            if(JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?",  
                    "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                FuncionarioData DAO = new FuncionarioData();
                if(DAO.excluir(Integer.parseInt(JLNumid.getText()))){
                    JOptionPane.showMessageDialog(this, "Excluido");
                    JBCancelarActionPerformed(evt);
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JBExcluirActionPerformed

    private void JBExcluirTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirTelActionPerformed
        try{
            int linha = JTTabelaTel.getSelectedRow();
            DefaultTableModel mp = (DefaultTableModel)JTTabelaTel.getModel();
            mp.removeRow(linha);
            JBExcluirTel.setEnabled(false);
            JTTabelaTel.getSelectionModel().clearSelection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JBExcluirTelActionPerformed

    private void JTTabelaTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTTabelaTelMouseClicked
        try{
            int linha = JTTabelaTel.getSelectedRow();
            if(linha > -1)
                JBExcluir.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JTTabelaTelMouseClicked

    private void JTTabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTTabelaDadosMouseClicked
        try{
            int linha = JTTabelaDados.getSelectedRow();
            if(linha>-1){
                JLNumid.setText("" + listaFuncionarios.get(linha).getId());
                JTFNome.setText(listaFuncionarios.get(linha).getNome());
                JTFCidade.setText(listaFuncionarios.get(linha).getCidade());
                JTFRua.setText(listaFuncionarios.get(linha).getRua());
                JTFBairro.setText(listaFuncionarios.get(linha).getBairro());
                JTFEmail.setText(listaFuncionarios.get(linha).getEmail());
                jftfCpf.setText(listaFuncionarios.get(linha).getCpf());
                jftfDataNasc.setText(listaFuncionarios.get(linha).getData_nasc());
                JTFLogin.setText(listaFuncionarios.get(linha).getLogin());
                jftfCep.setText(listaFuncionarios.get(linha).getCep());
                JTFNumero.setText(listaFuncionarios.get(linha).getNumero());
                jcbEstado.setSelectedItem(listaFuncionarios.get(linha).getEstado());
                JTFCompl.setText(listaFuncionarios.get(linha).getComplemento());
                jcbSexo.setSelectedItem(listaFuncionarios.get(linha).getSexo());
                jftfRg.setText(listaFuncionarios.get(linha).getRg());
                jtfSenha.setText(listaFuncionarios.get(linha).getSenha());
                JTFObservacoes.setText(listaFuncionarios.get(linha).getObservacoes());
                JCBCargo.setSelectedItem(listaFuncionarios.get(linha).getCargo());
                DefaultTableModel mp = (DefaultTableModel) JTTabelaTel.getModel();
                JTFEmail.setText(listaFuncionarios.get(linha).getEmail());
                mp.setNumRows(0);
                for(TelefoneModel tel: listaFuncionarios.get(linha).getTelefones()){
                    mp.addRow(new String[]{"" + tel.getDdd(), "" + tel.getNumero(), tel.getTipo_tel()});
                }
                JBEditar.setEnabled(true);
                JBExcluir.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JTTabelaDadosMouseClicked

    private void jftfDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfDataNascActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionarTel;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBEditar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBExcluirTel;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JComboBox<String> JCBCargo;
    private javax.swing.JComboBox<String> JCBTipoTel;
    private javax.swing.JLabel JLBairro;
    private javax.swing.JLabel JLCargo;
    private javax.swing.JLabel JLCep;
    private javax.swing.JLabel JLCidade;
    private javax.swing.JLabel JLCompl;
    private javax.swing.JLabel JLCpf;
    private javax.swing.JLabel JLData_nasc;
    private javax.swing.JLabel JLDdd;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLEstado;
    private javax.swing.JLabel JLId;
    private javax.swing.JLabel JLLogin;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLNumTel;
    private javax.swing.JLabel JLNumero;
    private javax.swing.JLabel JLNumid;
    private javax.swing.JLabel JLObservacoes;
    private javax.swing.JLabel JLPesquisar;
    private javax.swing.JLabel JLRg;
    private javax.swing.JLabel JLRua;
    private javax.swing.JLabel JLSenha;
    private javax.swing.JLabel JLSexo;
    private javax.swing.JLabel JLTelefone;
    private javax.swing.JPanel JPTabela;
    private javax.swing.JScrollPane JSPTabela;
    private javax.swing.JScrollPane JSPTabelaTel;
    private javax.swing.JTextField JTFBairro;
    private javax.swing.JTextField JTFCidade;
    private javax.swing.JTextField JTFCompl;
    private javax.swing.JTextField JTFDdd;
    private javax.swing.JTextField JTFEmail;
    private javax.swing.JTextField JTFLogin;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFNumTel;
    private javax.swing.JTextField JTFNumero;
    private javax.swing.JTextField JTFObservacoes;
    private javax.swing.JTextField JTFPesquisar;
    private javax.swing.JTextField JTFRua;
    private javax.swing.JTable JTTabelaDados;
    private javax.swing.JTable JTTabelaTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfDataNasc;
    private javax.swing.JFormattedTextField jftfRg;
    private javax.swing.JTextField jtfSenha;
    // End of variables declaration//GEN-END:variables
    
    public void tratarCampos(boolean t){
        JTFNome.setEnabled(t);
        JTFCidade.setEnabled(t);
        JTFRua.setEnabled(t);
        JTFBairro.setEnabled(t);
        JTFEmail.setEnabled(t);
        jftfCpf.setEnabled(t);
        jftfDataNasc.setEnabled(t);
        JTFLogin.setEnabled(t);
        jftfCep.setEnabled(t);
        JTFNumero.setEnabled(t);
        jcbEstado.setEnabled(t);
        JTFCompl.setEnabled(t);
        jcbSexo.setEnabled(t);
        jftfRg.setEnabled(t);
        jtfSenha.setEnabled(t);
        JCBTipoTel.setEnabled(t);
        JTFDdd.setEnabled(t);
        JTFNumTel.setEnabled(t);
        JTFObservacoes.setEnabled(t);
        JCBCargo.setEnabled(t);
        JBAdicionarTel.setEnabled(t);
        JBExcluirTel.setEnabled(t);
    }
    
    public void limparCampos(){
        JLNumid.setText("0");
        JTFNome.setText(null);
        JTFCidade.setText(null);
        JTFRua.setText(null);
        JTFBairro.setText(null);
        JTFEmail.setText(null);
        jftfCpf.setText(null);
        jftfDataNasc.setText(null);
        JTFLogin.setText(null);
        jftfCep.setText(null);
        JTFNumero.setText(null);
        jcbEstado.setSelectedIndex(0);
        JTFCompl.setText(null);
        jcbSexo.setSelectedIndex(0);
        jftfRg.setText(null);
        jtfSenha.setText(null);
        JCBTipoTel.setSelectedIndex(0);
        JTFDdd.setText(null);
        JTFNumTel.setText(null);
        JTFObservacoes.setText(null);
        JCBCargo.setSelectedIndex(0);
    }
    
    public boolean validarCampos(){
        try{
            FuncionarioData func = new FuncionarioData();
            String msg = new String();
            if(JTFNome.getText().trim().length()<3)
            msg = "Verifique o nome";
            if(JTFEmail.getText().trim().length()<10 || !JTFEmail.getText().trim().contains("@"))
                msg += "\nVerifique o e-mail";
            if(jtfSenha.getText().trim().length() < 3 || jtfSenha.getText().trim().length() > 15)
                msg+= "\nVerifique a senha";
            if(jftfCpf.getText().trim().length() != 14)
                msg += "\nVerifique o CPF";
            if(jftfRg.getText().trim().length() != 12)
                msg+= "\nVerifique o RG";
            if(jftfCep.getText().trim().length() != 10)
                msg += "\nVerifique o Cep";
            if(JTFRua.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da rua";
            if(JTFBairro.getText().trim().length() < 3)
                msg+= "\nVerifique o nome o bairro";
            if(JTFCidade.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da cidade";
            if(JTFRua.getText().trim().length() < 3)
                msg+= "\nVerifique o nome da rua";
            if(JTFNumero.getText().trim().length() > 5)
                msg+= "\nVerifique o numero do endereço";
            if(jcbEstado.getSelectedIndex() == 0)
                msg+= "\nVerifique o estado";
            if(JTFLogin.getText().trim().length() < 3)
                msg+= "\nVerifique o login";
            if(jftfDataNasc.getText().trim().length() != 10)
                msg+= "\nVerifique a data de nascimento";
            if(jcbSexo.getSelectedIndex() == 0)
                msg +="Verifique o sexo";
            if(JCBCargo.getSelectedIndex() == 0)
                msg += "\nVerifique o cargo";
            if(func.verificaLoginEx(JTFLogin.getText(), jtfSenha.getText()))
                msg += "Login ou senha já em uso!";
            if(msg.isEmpty()) return true;
            else{
                JOptionPane.showMessageDialog(this, "Erros: " + msg, "Validação", JOptionPane.ERROR_MESSAGE);      
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        return false;
    }
    
    public boolean preencherObjeto() throws Exception{
        obj.setId(Integer.parseInt(JLNumid.getText()));
        obj.setNome(JTFNome.getText());
        obj.setCidade(JTFCidade.getText());
        obj.setRua(JTFRua.getText());
        obj.setBairro(JTFBairro.getText());
        obj.setEmail(JTFEmail.getText());
        obj.setCpf(jftfCpf.getText());
        obj.setData_nasc(jftfDataNasc.getText());
        obj.setLogin(JTFLogin.getText());
        obj.setCep(jftfCep.getText());
        obj.setNumero(JTFNumero.getText());
        obj.setEstado(jcbEstado.getSelectedItem().toString());
        obj.setComplemento(JTFCompl.getText());
        obj.setSexo(jcbSexo.getSelectedItem().toString());
        obj.setRg(jftfRg.getText());
        obj.setSenha(jtfSenha.getText());
        obj.setObservacoes(JTFObservacoes.getText());
        obj.setCargo(JCBCargo.getSelectedItem().toString());
        DefaultTableModel mp = (DefaultTableModel)JTTabelaTel.getModel();
        for(int i=0; i<mp.getRowCount(); i++){
            TelefoneModel telefone = new TelefoneModel();
            telefone.setDdd(Integer.parseInt(mp.getValueAt(i, 0).toString()));
            telefone.setNumero(Integer.parseInt(mp.getValueAt(i, 1).toString()));
            telefone.setTipo_tel(mp.getValueAt(i, 2).toString());
            obj.adicionarTelefone(telefone);
        }
        return true;
    }
    
    public void inicializarTela(){
        limparCampos();
        tratarCampos(false);
        JBSalvar.setEnabled(false);
        JBEditar.setEnabled(false);
        JBCancelar.setEnabled(false);
        JBExcluir.setEnabled(false);
    }
    
    public void limparTabelaTel(){
        DefaultTableModel tabela = (DefaultTableModel) JTTabelaTel.getModel();
        for(int i = tabela.getRowCount() - 1; i>=0; i--)
            tabela.removeRow(i);
    }
    public void limparTabDadosFunc(){
        DefaultTableModel tabela = (DefaultTableModel) JTTabelaDados.getModel();
        for(int i = tabela.getRowCount() - 1; i>=0; i--)
            tabela.removeRow(i);
        JTFPesquisar.setText("");
    }
    
    public boolean verificaTelRep(DefaultTableModel mp, String ddd, String numero){
        int quant = mp.getRowCount();
        while(quant != 0){
            if(mp.getValueAt(mp.getRowCount() - 1, 0).equals(ddd) && mp.getValueAt(mp.getRowCount() - 1, 1).equals(numero))
                return true;
            quant--;
        }
        return false;
    }
}
